### ISSUE TITLE
OpenSSL 1.1.x support

### ISSUE THREAD

**Issue by voxik** [net-ssh/net-ssh#503]
Trying to run test suite against Ruby 2.4, I observe one test failure:

~~~
  1) Error:
Authentication::TestAgent#test_add_dsa_cert_identity:
NameError: uninitialized constant OpenSSL::Digest::DSS1
    /builddir/build/BUILD/rubygem-net-ssh-4.1.0/usr/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/openssl.rb:117:in `ssh_do_sign'
    /builddir/build/BUILD/rubygem-net-ssh-4.1.0/usr/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/authentication/certificate.rb:80:in `sign!'
    /builddir/build/BUILD/rubygem-net-ssh-4.1.0/usr/share/gems/gems/net-ssh-4.1.0/test/authentication/test_agent.rb:401:in `make_cert'
    /builddir/build/BUILD/rubygem-net-ssh-4.1.0/usr/share/gems/gems/net-ssh-4.1.0/test/authentication/test_agent.rb:258:in `test_add_dsa_cert_identity'
~~~

This is apparently due to OpenSSL 1.1.x and Ruby OpenSSL 2.0.x: https://github.com/ruby/openssl/commit/aeadc753c09a1d77636feaf87aca11ca19795fb6 .

**Comment by voxik** [comment]
Forgot to add that I am testing this on Fedora Rawhide.

**Comment by mfazekas** [comment]
@voxik Thanks for the report. yes it looks like `DSS1` is not available on openssl 1.1 or later `openssl version` 

I assume we need to disable the code that depends on those unless they are available.

**Comment by Try2Code** [comment]
this error is still present - tested on archlinux (openssl-1.1.0, net/ssh-4.2.0)

**Comment by Try2Code** [comment]
I patch net-ssh-4.2.0/lib/net/ssh/transport/openssl.rb to use SHA1 instead

**Comment by pvalena** [comment]
@Try2Code can you please link to the patch or commit?

**Comment by Try2Code** [comment]
my locally patched version against latest net-ssh revision

```diff
--- lib/net/ssh/transport/openssl.rb	2018-02-08 00:03:09.320105062 +0100
+++ /home/ram/.gem/ruby/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/openssl.rb	2018-01-15 09:09:30.589198839 +0100
@@ -109,12 +109,12 @@
            OpenSSL::ASN1::Integer(sig_r),
            OpenSSL::ASN1::Integer(sig_s)
         ])
-        return verify(OpenSSL::Digest::DSS1.new, a1sig.to_der, data)
+        return verify(OpenSSL::Digest::SHA1.new, a1sig.to_der, data)
       end
 
       # Signs the given data.
       def ssh_do_sign(data)
-        sig = sign( OpenSSL::Digest::DSS1.new, data)
+        sig = sign( OpenSSL::Digest::SHA1.new, data)
         a1sig = OpenSSL::ASN1.decode( sig )
 
         sig_r = a1sig.value[0].value.to_s(2)
```

**Comment by pvalena** [comment]
Thanks!

**Comment by mfazekas** [comment]
@Try2Code can you submit a PR with this change?

**Comment by Try2Code** [comment]
done:  #571

**Comment by asheynkman** [comment]
Hi guys,
 Is there plan to have this available part of the standard gem ? or we have to apply the patch?

thanks

**Comment by mfazekas** [comment]
@asheynkman should be fixed on master, isn't it?

**Comment by asheynkman** [comment]
@mfazekas No we use  net-ssh (4.2.0) and still having issue with above

**Comment by Try2Code** [comment]
@asheynkman master is at 5.0.x afaik

**Comment by asheynkman** [comment]
@Try2Code ys but is publicly released yet ? i can only see beta version

**Comment by mfazekas** [comment]
@asheynkman i've just released beta1 at https://rubygems.org/gems/net-ssh/versions/5.0.0.beta1

**Comment by wk** [comment]
@mfazekas Is there any chance for a backport and release of net-ssh 4.2.1 with this change? 

Seeing this in ytti/oxidized#1580 where the project still depends on net-ssh 4.x for backwards compatibility with Ruby 2.0, but users are finding themselves on newer distributions that include OpenSSL 1.1 with increasing frequency.

**Comment by wk** [comment]
@mfazekas thanks for looking into this! Many users of oxidized operate IT infrastructures in a range of highly regulated industries and settings. In such environments, it is not uncommon for operations support system deployments to have lifecycles of 5-7 years. 

To sustain such long lifecycles, some operators choose for long term support distributions (RHEL, ...) at the base of their infrastructure stack at the beginning of a project, with the intention of the stack to remain largely immutable for the duration of the lifecycle. The entire stack then undergoes extensive conformity tests and audits (occasionally done by external parties) and is maintained throughout the lifecycle with as little volatility as possible - typically with nothing but backported security patches applied after a change management process.

One widely used distribution in such settings, RHEL (and CentOS) 7, shipped with Ruby 2.0 - and continues to power many deployments to this day. In such environments, users often find it difficult (at least in terms of process and procedure) to justify upgrading the Ruby interpreter. With this in mind, oxidized attempts to maintain the broadest backward compatibility possible for their benefit.

**Comment by trevor-vaughan** [comment]
Agree with the proposal to backport to the 4.2.x series due to Enterprise lifecycles.

**Comment by mfazekas** [comment]
I'm sorry but this project has no resources for backporting. I recommend either forking - or sponsoring net-ssh.
